CREATE TABLE X 
(
    SELLER_ID INT,
    CATEGORY VARCHAR(50),
    SALES INT
)

INSERT INTO X VALUES (1,'BOOK',258)
INSERT INTO X VALUES (2,'ELECTRONICS',299)
INSERT INTO X VALUES (3,'ELECTRONICS',123)
INSERT INTO X VALUES (4,'BOOK',272)
INSERT INTO X VALUES (5,'FMCG',485)
INSERT INTO X VALUES (6,'BOOK',187)
INSERT INTO X VALUES (7,'FMCG',349)
INSERT INTO X VALUES (8,'FMCG',61)
INSERT INTO X VALUES (9,'ELECTRONICS',321)
INSERT INTO X VALUES (10,'FMCG',20)

SELECT * FROM X

CREATE TABLE Y 
(
    AWARD_YEAR INT,
    AWARE VARCHAR(100),
    SELLER INT
)

INSERT INTO Y VALUES (2017,'BEST SELLER',9)
INSERT INTO Y VALUES (2018,'BEST SELLER',5)
INSERT INTO Y VALUES (2017,'BEST OPERATIONS',5)
INSERT INTO Y VALUES (2018,'BEST QUALITY',10)
INSERT INTO Y VALUES (2018,'BEST OPERATIONS',6)
INSERT INTO Y VALUES (2017,'BEST SELLER',4)
INSERT INTO Y VALUES (2017,'BEST OPERATIONS',5)
INSERT INTO Y VALUES (2017,'BEST QUALITY',7)
INSERT INTO Y VALUES (2017,'BEST QUALITY',10)

SELECT * FROM Y

-- Tìm ra best seller cho từng category
-- 1. Tìm ra số sales lớn nhất theo từng category
-- 2. Tìm ra sellers tương ứng số sales (1)

WITH MA_SA AS (
    SELECT CATEGORY , MAX(SALES) AS MAX_SALES
    FROM X
    GROUP BY CATEGORY
)

SELECT SELLER_ID, A.CATEGORY, MAX_SALES
FROM MA_SA AS A  
INNER JOIN X ON A.MAX_SALES = X.SALES AND A.CATEGORY = X.CATEGORY

-- Write SQL query to find of 3 best sellers in (a), how many award did they received in 20217
WITH MA_SA AS (
    SELECT CATEGORY , MAX(SALES) AS MAX_SALES
    FROM X
    GROUP BY CATEGORY
)

SELECT SELLER_ID, A.CATEGORY, COUNT(AWARD_YEAR) AS AWARD_IN_2017
FROM MA_SA AS A  
    INNER JOIN X ON A.MAX_SALES = X.SALES AND A.CATEGORY = X.CATEGORY
    INNER JOIN Y ON X.SELLER_ID = Y.SELLER
WHERE AWARD_YEAR = 2017
GROUP BY SELLER_ID, A.CATEGORY